# Generated by Django 2.2.5 on 2020-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('casual_leave', models.CharField(max_length=200)),
                ('earned_leave', models.CharField(max_length=200)),
                ('sick_leave', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=200)),
                ('reason_msg', models.TextField()),
                ('available_days', models.CharField(max_length=200)),
                ('requesting_days', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
