# Generated by Django 2.2.5 on 2020-09-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_type', models.CharField(max_length=200)),
                ('reason_msg', models.TextField()),
                ('available_days', models.CharField(max_length=200)),
                ('requesting_days', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('status', models.SmallIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('casual_leave', models.CharField(max_length=200)),
                ('earned_leave', models.CharField(max_length=200)),
                ('sick_leave', models.CharField(max_length=200)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee')),
            ],
        ),
    ]
