# Generated by Django 2.2.5 on 2020-09-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leave', '0001_initial'),
        ('user_invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee'),
        ),
    ]
