# Generated by Django 2.2.5 on 2020-09-03 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='monthyear',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='leaverequest',
            old_name='reason',
            new_name='reason_msg',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='available_days',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requesting_days',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
