# Generated by Django 2.2.5 on 2020-10-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20201003_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='expense_file',
            field=models.FileField(blank=True, null=True, upload_to='leave_file/'),
        ),
    ]
