# Generated by Django 2.2.5 on 2020-10-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leaverequest_expense_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='expense_file',
            new_name='leave_file',
        ),
    ]
