# Generated by Django 2.2.5 on 2020-09-07 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('ctc', models.PositiveIntegerField()),
                ('joining_date', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must consist of 10 digits.(Like 1234567890)', regex='^\\+?1?\\d{9,12}$')])),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Employee Details',
                'ordering': ['-id'],
            },
        ),
    ]
