# Generated by Django 2.2.5 on 2020-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200918_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
