# Generated by Django 2.2.5 on 2020-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200918_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='expense_date',
            field=models.DateField(),
        ),
    ]
