# Generated by Django 2.2.13 on 2020-09-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200918_0810'),
        ('expenses', '0004_auto_20200918_0914'),
    ]

    operations = [
    ]
