# Generated by Django 2.2.5 on 2020-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20200919_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='expense_file',
            field=models.FileField(blank=True, null=True, upload_to='expense_file/'),
        ),
    ]
