# Generated by Django 2.2.5 on 2020-09-10 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_invoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acc_no', models.CharField(max_length=200)),
                ('bank', models.CharField(max_length=200)),
                ('other_bank', models.CharField(blank=True, max_length=300, null=True)),
                ('ifsc_other', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee')),
            ],
        ),
    ]
