# Generated by Django 2.2.5 on 2020-09-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
