# Generated by Django 2.2.5 on 2020-09-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0003_userdetail_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='employee_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='salary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
