# Generated by Django 2.2.5 on 2020-09-29 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0004_auto_20200929_1148'),
        ('manage_user', '0004_auto_20200925_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_manager',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='report_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_invoice.Employee'),
        ),
    ]
