# Generated by Django 2.2.5 on 2020-09-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0005_auto_20200929_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='report_to',
        ),
    ]
