# Generated by Django 2.2.13 on 2020-10-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0006_remove_userdetail_report_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='designation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
