# Generated by Django 2.2.13 on 2020-10-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0007_userdetail_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='employee_id',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
