# Generated by Django 2.2.5 on 2020-08-20 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pnone_no',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(default=datetime.datetime(2020, 8, 20, 11, 21, 29, 479502, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
