# Generated by Django 2.2.5 on 2020-08-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0002_auto_20200820_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base', models.CharField(blank=True, max_length=300, null=True)),
                ('difficultnp', models.CharField(blank=True, max_length=300, null=True)),
                ('extra_hours', models.CharField(blank=True, max_length=300, null=True)),
                ('file_attach', models.CharField(blank=True, max_length=300, null=True)),
                ('duplicate_solic', models.CharField(max_length=300)),
                ('entity_cont_wrong', models.CharField(max_length=300)),
                ('false_referal', models.CharField(max_length=300)),
                ('fraudsolic_update', models.CharField(max_length=300)),
                ('source_ret_wo_res', models.CharField(max_length=300)),
                ('missed_bond', models.CharField(max_length=300)),
                ('missed_categories', models.CharField(max_length=300)),
                ('missed_solic_src', models.CharField(max_length=300)),
                ('missed_file', models.CharField(max_length=300)),
                ('missed_link', models.CharField(max_length=300)),
                ('missed_term', models.CharField(max_length=300)),
                ('not_posted_lead', models.CharField(max_length=300)),
                ('other_error', models.CharField(max_length=300)),
                ('other_serious_err', models.CharField(max_length=300)),
                ('refreshing_wds', models.CharField(max_length=300)),
                ('wage_not_selected', models.CharField(max_length=300)),
                ('skipped_solic', models.CharField(max_length=300)),
                ('source_ret_wo_note', models.CharField(max_length=300)),
                ('unjustified_absence', models.CharField(max_length=300)),
                ('wrong_pre_bid', models.CharField(max_length=300)),
                ('wrong_categories', models.CharField(max_length=300)),
                ('wrong_geo_location', models.CharField(max_length=300)),
                ('incorrect_scope', models.CharField(max_length=300)),
                ('wrong_text_format', models.CharField(max_length=300)),
                ('auth_day_off', models.CharField(max_length=300)),
                ('unauth_day_off', models.CharField(max_length=300)),
                ('is_approved', models.SmallIntegerField(default=0)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee')),
            ],
        ),
    ]
