# Generated by Django 2.2.5 on 2020-09-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0002_invoice_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='leaves',
        ),
    ]
