# Generated by Django 2.2.5 on 2020-08-24 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0003_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_invoice.Employee'),
        ),
    ]
