# Generated by Django 2.2.5 on 2020-08-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0004_auto_20200824_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='add_auth_days',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
