# Generated by Django 2.2.5 on 2020-10-03 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0004_auto_20200929_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='report_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empreport_to', to='user_invoice.Employee'),
        ),
    ]
