# Generated by Django 2.2.5 on 2020-08-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0005_rate_add_auth_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_date', models.DateField()),
                ('monthdate', models.DateField()),
                ('emp_type', models.CharField(blank=True, max_length=150, null=True)),
                ('additional_auth_days', models.CharField(blank=True, max_length=100, null=True)),
                ('wds_source_checked_completely', models.CharField(blank=True, max_length=200, null=True)),
                ('new_solicitation_entered_correctly', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_solicitation_by_addenda', models.CharField(blank=True, max_length=200, null=True)),
                ('extra_hours_worked', models.CharField(blank=True, max_length=200, null=True)),
                ('file_attached', models.CharField(blank=True, max_length=200, null=True)),
                ('authorised_day_off', models.CharField(blank=True, max_length=200, null=True)),
                ('total_working_days', models.CharField(blank=True, max_length=200, null=True)),
                ('total_days_worked', models.CharField(blank=True, max_length=200, null=True)),
                ('duplicate_solic', models.CharField(blank=True, max_length=200, null=True)),
                ('entity_cont_wrong', models.CharField(blank=True, max_length=200, null=True)),
                ('false_referal', models.CharField(blank=True, max_length=200, null=True)),
                ('fraudulent_solicitation_update', models.CharField(blank=True, max_length=200, null=True)),
                ('source_returned_without_good_res', models.CharField(blank=True, max_length=200, null=True)),
                ('missed_bidbond_and_specs', models.CharField(blank=True, max_length=200, null=True)),
                ('missed_categories', models.CharField(blank=True, max_length=200, null=True)),
                ('missed_solic_or_addend_from_source', models.CharField(blank=True, max_length=200, null=True)),
                ('missed_incorrect_filetype', models.CharField(blank=True, max_length=200, null=True)),
                ('missing_or_wrong_outside_link', models.CharField(blank=True, max_length=200, null=True)),
                ('missing_or_wrong_term_contract', models.CharField(blank=True, max_length=200, null=True)),
                ('not_posted_as_lead', models.CharField(blank=True, max_length=200, null=True)),
                ('other_error', models.CharField(blank=True, max_length=200, null=True)),
                ('other_serious_error', models.CharField(blank=True, max_length=200, null=True)),
                ('refreshing_wds_page_to_diff_source', models.CharField(blank=True, max_length=200, null=True)),
                ('prevailing_wage_not_selected', models.CharField(blank=True, max_length=200, null=True)),
                ('skipped_solicitation', models.CharField(blank=True, max_length=200, null=True)),
                ('source_returned_without_a_note', models.CharField(blank=True, max_length=200, null=True)),
                ('unexcused_unjustified_absence', models.CharField(blank=True, max_length=200, null=True)),
                ('wrongbid_prebid_mandatory', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_categories', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_geographic_location', models.CharField(blank=True, max_length=200, null=True)),
                ('incomplete_and_incorrect_scope', models.CharField(blank=True, max_length=200, null=True)),
                ('wrong_text_format', models.CharField(blank=True, max_length=200, null=True)),
                ('authorized_day_off', models.CharField(blank=True, max_length=200, null=True)),
                ('unauthorised_day_off', models.CharField(blank=True, max_length=200, null=True)),
                ('total_deduction', models.CharField(blank=True, max_length=200, null=True)),
                ('total_payable', models.CharField(blank=True, max_length=200, null=True)),
                ('is_approved', models.SmallIntegerField(default=0)),
                ('emp_ownwer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee')),
            ],
        ),
    ]
