# Generated by Django 2.2.5 on 2020-10-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0006_productionreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='additional_auth_days',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='difficult_and_nonproductive_source',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='extra_days_worked',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='extra_hours_worked',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='file_attached',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='new_entities_added',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='new_solicitation_entered_correctly',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ph_added_to_bid_list',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ph_deleted_in_bid_list',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ph_edited_in_bid_list',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='updated_solicitation_by_addenda',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='wds_source_checked_completely',
        ),
    ]
