# Generated by Django 2.2.5 on 2020-08-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0007_auto_20200826_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='difficult_and_nonproductive_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
