# Generated by Django 2.2.5 on 2020-10-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0008_auto_20201014_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file_upload',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fixed_salary',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='production_pay',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wds_edit',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wds_import',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wds_solicitation',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wds_source',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
    ]
