# Generated by Django 2.2.5 on 2020-08-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0009_auto_20200827_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_pay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='total_pay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
