# Generated by Django 2.2.5 on 2020-10-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0009_auto_20201015_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='wds_solicitation',
            new_name='wds_solicitaion',
        ),
    ]
