# Generated by Django 2.2.5 on 2020-10-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0012_auto_20201019_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.IntegerField(max_length=200),
        ),
    ]
