# Generated by Django 2.2.5 on 2020-09-07 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0013_auto_20200902_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_invoice.Rate'),
        ),
    ]
