# Generated by Django 2.2.5 on 2020-10-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0013_auto_20201019_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlydeduction',
            name='month',
            field=models.IntegerField(max_length=200, unique=True),
        ),
    ]
