# Generated by Django 2.2.5 on 2020-09-08 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0014_invoice_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
