# Generated by Django 2.2.13 on 2020-10-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0002_auto_20200915_0516'),
        ('user_invoice', '0015_auto_20201019_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account_management.AccountDetails'),
        ),
    ]
