# Generated by Django 2.2.13 on 2020-10-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0016_invoice_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='auth_day_rate',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
    ]
