# Generated by Django 2.2.13 on 2020-10-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0017_invoice_auth_day_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='emp_ownwer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee'),
            preserve_default=False,
        ),
    ]
