# Generated by Django 2.2.13 on 2020-10-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0019_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='advance',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='commission',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='dollar_rate',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emp_esi_id',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emp_ins_fund',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='emp_pf_id',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='percent_pf_prev_month',
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
    ]
