# Generated by Django 2.2.13 on 2020-10-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0021_dollarrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='esi_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pf_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
