# Generated by Django 2.2.13 on 2020-10-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0022_auto_20201028_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('banner_name', models.CharField(max_length=200)),
                ('banner_pic', models.FileField(upload_to='banner/')),
            ],
        ),
    ]
