# Generated by Django 2.2.13 on 2020-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0023_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='check_cash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='check_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payslip_bank',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payslip_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
