# Generated by Django 2.2.13 on 2020-10-30 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0024_auto_20201030_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='check_cash',
            new_name='cheque_cash',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='check_no',
            new_name='cheque_no',
        ),
    ]
