# Generated by Django 2.2.13 on 2020-11-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_invoice', '0025_auto_20201030_0555'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaySlipOthers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month_year', models.DateField()),
                ('emp_state_ins_fund', models.CharField(blank=True, default=0, max_length=200)),
                ('percent_pf_prev_month', models.CharField(blank=True, default=0, max_length=200)),
                ('advance', models.CharField(blank=True, default=0, max_length=200)),
                ('commission', models.CharField(blank=True, default=0, max_length=200)),
                ('other_field', models.CharField(blank=True, max_length=200, null=True)),
                ('other_value', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_invoice.Employee')),
            ],
        ),
    ]
